services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Oveleon\ContaoGoogleRecommendationBundle\:
    resource: '../src/'
    exclude: '../src/{Model,DependencyInjection,Resources}'
